#!/usr/bin/python
#
# kvm_host_numad_enabled
# Health check program for the Linux Health Checker
#
# Copyright IBM Corp. 2012
#
# Author(s): Prem Karat <prem.karat@linux.vnet.ibm.com>
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors: See file CONTRIBUTORS which is part of this package
#
import os, re, sys, commands

# Import local modules
checklib = os.path.join(os.environ['LNXHC_LIBDIR'], 'python')
sys.path.insert(0, checklib)
from check.base import *
from check.util import *


def kvm_numad():
    SYSINFO_NUMAD = os.environ["LNXHC_SYSINFO_rpm_qa"]
    rpm_qa = lnxhc_get_fcontent(SYSINFO_NUMAD)
    numad = re.findall(r"^numad", rpm_qa, re.M)
    if not numad:
        lnxhc_exception("numad_package_notfound")

    SYSINFO_NUMAD_STARTUP = os.environ["LNXHC_SYSINFO_EXIT_CODE_" \
                                                "chkconfig_numad"]
    if int(SYSINFO_NUMAD_STARTUP):
        lnxhc_exception("chkconfig_numad_off")

    # check the status of numad service
    SYSINFO_NUMAD_RC = os.environ["LNXHC_SYSINFO_EXIT_" \
                              "CODE_service_numad_status"]
    if int(SYSINFO_NUMAD_RC):
        lnxhc_exception("numad_service_failed")

def main():
    kvm_numad()


if __name__ == '__main__':
    main()
