#!/usr/bin/env perl
#
# read_sysfs
#   Generic program to read the sysfs attribs.
#
# Copyright IBM Corp. 2013
#
# Author(s): Manik Bajpai <manibajp@in.ibm.com>
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors: See file CONTRIBUTORS which is part of this package
#
#
use warnings;
use strict;
use Fcntl ':mode';

sub dumpfile($)
{
	my ($filename) = @_;
	my $mode = (stat("$filename"))[2];
	my $fh;
	my $line;

	return if !(S_ISREG($mode) && (S_IRUSR & $mode));

	open($fh, "<", $filename) || die("$filename: $!\n");

	while ($line = <$fh>) {
		chomp($line);
		print "$filename\0$line\n";
	}
	close($fh);
}

sub main
{
	foreach my $filename (@ARGV) {
		dumpfile($filename);
	}
}
&main();
__DATA__
__END__
##USAGE ./read_sysfs /sys/bus/ccw/drivers/zfcp/[[:xdigit:]]*/0x*/*
##USAGE ./read_sysfs /sys/bus/ccw/drivers/zfcp/[[:xdigit:]]*/*
