#!/usr/bin/perl
#
# crypto_z_module_loaded
#   Health check program for the Linux Health Checker
#
# Copyright IBM Corp. 2013
#
# Author(s): Peter Oberparleiter <peter.oberparleiter@de.ibm.com>
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors: See file CONTRIBUTORS which is part of this package
#

use strict;
use warnings;

use lib $ENV{"LNXHC_LIBDIR"};
use LNXHC::Check::Base;

#
# Global variables
#

# Return code for sysinfo item 'dev_node'
my $rc_dev_node = $ENV{"LNXHC_SYSINFO_EXIT_CODE_dev_node"};

if ($rc_dev_node) {
	lnxhc_exception("module_not_loaded");
}

exit(0);
