#!/usr/bin/python
#
# kvm_guest_clock_policy

# Health check program for the Linux Health Checker
#
# Copyright IBM Corp. 2012
#
# Author(s): Prem Karat <prem.karat@linux.vnet.ibm.com>
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors: See file CONTRIBUTORS which is part of this package
#
import os, re, sys, commands

# Import local modules
checklib = os.path.join(os.environ['LNXHC_LIBDIR'], 'python')
sys.path.insert(0, checklib)
from check.base import *
from check.util import *

def lnxhc_readlines(filename):
    f = open(filename, "rU")
    buf = f.read()
    f.close()
    return buf

def mem_virtio():
    SYSINFO_VIRTIOINFO = os.environ["LNXHC_SYSINFO_guest_mem_info"]
    domains = lnxhc_readlines(SYSINFO_VIRTIOINFO)
    if domains:
        lnxhc_exception("memballoon_virtio_notset")
        print domains


def main():
    mem_virtio()


if __name__ == '__main__':
    main()
