#!/usr/bin/python
#
# kvm_host_ksm_disabled
# Health check program for the Linux Health Checker
#
# Copyright IBM Corp. 2012
#
# Author(s): Prem Karat <prem.karat@linux.vnet.ibm.com>
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors: See file CONTRIBUTORS which is part of this package
#
import os, re, sys, commands

# Import local modules
checklib = os.path.join(os.environ['LNXHC_LIBDIR'], 'python')
sys.path.insert(0, checklib)
from check.base import *
from check.util import *



def vmdirty_background_ratio():
    SYSINFO_VMDIRTY_RATIO = os.environ["LNXHC_SYSINFO_sysctl_vmdirty_background_ratio"]
    PARAM_DIRTY_RATIO = os.environ["LNXHC_PARAM_warn_vmdirty_background_ratio"]
    dirty_bg_ratio = lnxhc_get_fcontent(SYSINFO_VMDIRTY_RATIO)
    dratio = re.findall("vm.dirty_background_ratio = (\d*)", dirty_bg_ratio)
    if int(dratio[0]) != int(PARAM_DIRTY_RATIO):
        lnxhc_exception("warn_vmdirty_background_ratio")
        lnxhc_exception_var("vmdirty_background_ratio", int(dratio[0]))

def main():
    vmdirty_background_ratio()


if __name__ == '__main__':
    main()
