#!/usr/bin/python
#
# kvm_host_virbr0_exists
# Health check program for the Linux Health Checker
#
# Copyright IBM Corp. 2012
#
# Author(s): Prem Karat <prem.karat@linux.vnet.ibm.com>
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors: See file CONTRIBUTORS which is part of this package
#

import os, re, sys, commands

# Import local modules
checklib = os.path.join(os.environ['LNXHC_LIBDIR'], 'python')
sys.path.insert(0, checklib)
from check.base import *
from check.util import *


def rm_virbr0():
    SYSINFO_RMVIRBR0_RC = os.environ["LNXHC_SYSINFO_EXIT_CODE_virbr0_exists"]

    if not int(SYSINFO_RMVIRBR0_RC):
        lnxhc_exception("virbr0_exists")


if __name__ == '__main__':
  rm_virbr0()

