#!/usr/bin/perl
#
# scsi_dev_state
#   Health check program for the Linux Health Checker
#
# Copyright IBM Corp. 2013
#
# Author(s): Nageswara R Sastry <nasastry@in.ibm.com>
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors: See file CONTRIBUTORS which is part of this package
#

use strict;
use warnings;

use lib $ENV{"LNXHC_LIBDIR"};
use LNXHC::Check::Base;
use LNXHC::Check::Util qw/:proc/;

#
# Global variables
#

# Exception IDs
my $LNXHC_EXCEPTION_NOT_USABLE = "not_usable";

# Path to the file containing data for sysinfo item 'devices_data'.
my $sysinfo_devices_data = $ENV{"LNXHC_SYSINFO_devices_data"};

my $handle;
my %data_hash;

# Verifying whether fc_transport class is enabled or not
if (-z $sysinfo_devices_data) {
	lnxhc_fail_dep("No SCSI devices found");
}

open ($handle, "<", $sysinfo_devices_data) or
die("Couldn't open file: $sysinfo_devices_data: $!\n");

while (my $line = <$handle>) {
	chomp $line;
	my ($lun_dec, $wwpn, $lun, $state, $dev_block) = split/,/, $line;
	if(-z $lun_dec || -z $wwpn || -z $lun || -z $state ||
			-z $dev_block) {
		next;
	}
	if ($state ne "running") {
		push (@{$data_hash{$lun_dec}}, $lun, $wwpn, $state,
				$dev_block);
	}
}
close($handle);

if (%data_hash) {
	lnxhc_exception($LNXHC_EXCEPTION_NOT_USABLE);
	my @keys_list = sort(keys(%data_hash));
	lnxhc_exception_var("lun",
		"|SCSI Device|LUN|WWPN|State|Device Blocked");
	foreach my $lun (@keys_list) {
		my @list = @{$data_hash{$lun}};
		lnxhc_exception_var("lun",
			sprintf("|#%s|#%s|#%s|#%s|#%s", ($lun, @list)));
	}
	lnxhc_exception_var_list("lun_summ", \@keys_list, ", ");
}
exit(0);
