#!/bin/bash
#
# devices_data
#   Helper program to collect SCSI LUN state information.
#
# Copyright IBM Corp. 2013
#
# Author(s): Nageswara R Sastry <nasastry@in.ibm.com>
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors: See file CONTRIBUTORS which is part of this package
#



# Enable nullglob
shopt -s nullglob
# Collecting all remote ports
for SCSI_DEV_PATH in /sys/bus/scsi/devices/[0-9]:[0-9]:[0-9]* ;
do
	if [ -f "$SCSI_DEV_PATH/wwpn" -a -f "$SCSI_DEV_PATH/fcp_lun" \
		-a -f "$SCSI_DEV_PATH/state" \
		-a -f "$SCSI_DEV_PATH/device_blocked" ]; then
	read WWPN < $SCSI_DEV_PATH/wwpn
	read LUN < $SCSI_DEV_PATH/fcp_lun
	read STATE < $SCSI_DEV_PATH/state
	read DEV_BLOCK < $SCSI_DEV_PATH/device_blocked
	echo "${SCSI_DEV_PATH##*/},$WWPN,$LUN,$STATE,$DEV_BLOCK"
	fi
done
exit 0
